// Shared catalog of public plans. The `flagship` plan (motoblaker's cortesía
// perpetua) is intentionally NOT in this list — it is an internal SKU and
// should never be offered through the public pricing UI.

export const PUBLIC_PLANS = [
    {
        code: 'free',
        name: 'Free',
        tagline: 'Para probar MotoPartes sin compromiso',
        priceMonthly: 0,
        priceYearly: 0,
        cta: 'Comenzar gratis',
        highlight: false,
        features: [
            '30 órdenes de servicio por mes',
            '2 usuarios (mecánicos o admin)',
            '1 sesión de WhatsApp',
            '300 mensajes de WhatsApp / mes',
            '500 MB de fotos',
            'Portal público del cliente',
            'Soporte por comunidad',
        ],
    },
    {
        code: 'starter',
        name: 'Starter',
        tagline: 'Para talleres pequeños que arrancan formalmente',
        priceMonthly: 299,
        priceYearly: 2870,
        cta: 'Probar 14 días gratis',
        highlight: false,
        features: [
            '200 órdenes de servicio por mes',
            'Hasta 5 usuarios',
            '1 sesión de WhatsApp',
            '2,000 mensajes de WhatsApp / mes',
            '5 GB de fotos',
            'Branding básico (logo y colores)',
            '1 automatización de WhatsApp',
            'Soporte por correo (48h)',
        ],
    },
    {
        code: 'pro',
        name: 'Pro',
        tagline: 'El plan pensado para talleres activos',
        priceMonthly: 599,
        priceYearly: 5750,
        cta: 'Probar 14 días gratis',
        highlight: true,
        badge: 'El más popular',
        features: [
            'Órdenes ilimitadas',
            'Hasta 15 usuarios',
            '3 sesiones de WhatsApp',
            '10,000 mensajes de WhatsApp / mes',
            '25 GB de fotos',
            'Branding completo y folios personalizados',
            '5 tipos de automatizaciones',
            'Comisiones por mecánico',
            'Reportes avanzados',
            'Soporte por correo (24h)',
        ],
    },
    {
        code: 'business',
        name: 'Business',
        tagline: 'Para talleres con varias sucursales',
        priceMonthly: 1499,
        priceYearly: 14390,
        cta: 'Hablar con ventas',
        highlight: false,
        features: [
            'Todo lo del plan Pro',
            'Usuarios ilimitados',
            '10 sesiones de WhatsApp',
            'Mensajes ilimitados',
            '100 GB de fotos',
            'Dominio propio',
            'Automatizaciones ilimitadas',
            'API pública + webhooks',
            'Soporte prioritario por WhatsApp',
        ],
    },
];

export const FEATURE_BLOCKS = [
    { title: 'Órdenes de servicio', desc: 'Folios automáticos, estados, fotos antes y después, firma del cliente.' },
    { title: 'WhatsApp integrado', desc: 'Envía cotizaciones y actualizaciones desde el chat que tus clientes ya usan.' },
    { title: 'Clientes y motos', desc: 'Ficha por cliente con historial de motos, servicios y pagos.' },
    { title: 'Refacciones y pagos', desc: 'Control de costos, anticipos, método de pago y márgenes.' },
    { title: 'Comisiones por mecánico', desc: 'Reparte ganancias automáticamente según el porcentaje de cada mecánico.' },
    { title: 'Portal público', desc: 'Tu cliente ve el avance de su moto con un link único, sin crear cuenta.' },
];
